# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a34404ffdeaef03e1d41051bd7b7bfaa29e24c0568d93713ea91cb935731442d30bbef064b4a7414a4074c716b9b5017d55b46296e14dbeb615ce3ed31ee5de

test:
  secret_key_base: 8115b10b81816d829a87267a05cb13ccb63d2627a00992e2727b30083f627a66e3d88c15266b95aaf92abd249211851dc5410df9c7cf303e098a3f664610a574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
